[package]
name = "solana-pay-request"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wit-bindgen = "0.41.0"
wit-bindgen-rt = "0.41.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

pos-core = { path = "../../pos-core" }

[package.metadata.component]
package = "zeroclaw:plugin"
